graph TD
    CORE((FINCADIGI <br> Core App))

    %% Config & Data
    CORE --- DATOS(Gestión de Datos)
    DATOS --- Lotes[Lotes y Superficies]
    DATOS --- Inventario[Inventario y Almacén]
    DATOS --- Usuarios[Usuarios y Roles]

    %% Operaciones
    CORE --- OPERACIONES(Operaciones)
    OPERACIONES --- Siembras[Cronogramas de Siembra]
    OPERACIONES --- Monitoreo[Fitosanidad y Novedades]
    OPERACIONES --- Tareas[Flujo de Tareas]

    %% Vistas
    CORE --- VISTAS(Paneles de Trabajo)
    VISTAS --- Dashboard[Dashboard General]
    VISTAS --- PAdmin[Panel Admin / Encargado]
    VISTAS --- PEmpleado[Panel Empleado]
    VISTAS --- Alertas[Alertas y Reportes]
